RabbitMQ
Aleksandr-Naumov/DotNext-Moscow-2020 pull request #20
Opened 2021-03-21 20:24 UTC by Aleksandr-Naumov

2021-03-28 09:32 UTC, max-arshinov requested changes

2021-03-28 09:32 UTC, max-arshinov commented on Apps/WorkerService/Program.cs
> +                    services.AddTransient<IHandler<IEnumerable<ProductPurchased>>, OrderDomainEventHandler>();
Раз DbContext scoped, то это тоже делайте scoped, чтобы одинаковый лайфтайм был

2021-03-28 09:32 UTC, max-arshinov commented on Apps/WorkerService/DomainEventDispatcher.cs
>                  handler = _serviceProvider.GetService(GetHandlerType(typeof(IEnumerable<>).MakeGenericType(eventGroup.Key)));
Вы проверяли этот код? Какой Scope используется для работы с БД? Я бы открывал scope для диспетчеризации и сделал бы все scoped, раз DbContext scoped. Так будет понятно, что в рамках обработки сообщения все экземпляры в рамках scope создаются один раз

2021-04-02 17:02 UTC, max-arshinov requested changes

2021-04-02 17:02 UTC, max-arshinov commented on Apps/WorkerService/Scope/ScopedProcessingService.cs
> +                consumer.Received += (model, ea) =>
вы в цикле подписываетесь на реббит. Нужно один раз подписаться и просто ждать ```stoppingToken.IsCancellationRequested```

2021-04-02 17:02 UTC, max-arshinov commented on Apps/WorkerService/Scope/ScopedProcessingService.cs
> +        private IDomainEvent CreateEvent(DomainEventMessage message)
лучше сделайте IDomainEvent! здесь

2021-04-02 17:02 UTC, max-arshinov commented on Apps/WorkerService/Scope/ScopedProcessingService.cs
> +                return null!;
А здесь убрать !

2021-04-02 17:34 UTC, max-arshinov requested changes

2021-04-02 17:34 UTC, max-arshinov commented on Apps/WorkerService/Scope/ScopedProcessingService.cs
> +                consumer: consumer);
Забыли дожидаться canellationToken в конце метода. Сервис подпишется на ребит и закончит работу

2021-04-04 06:47 UTC, Aleksandr-Naumov commented on Apps/WorkerService/Scope/ScopedProcessingService.cs
> +                consumer: consumer);
сделал bool переменную _cancell, для проверки получили мы события или нет (если ДА, то вызывается запрос на отмену токена и выполнение заканчивается)

2021-04-10 17:00 UTC, merged