My work
Aleksandr-Naumov/DotNext-Moscow-2020 pull request #3
Opened 2021-02-05 17:58 UTC by Aleksandr-Naumov

2021-02-05 18:14 UTC, max-arshinov requested changes

2021-02-05 18:14 UTC, max-arshinov commented on Apps/HightechAngular.Web/Features/Account/CreateNewOrder/CreateNewOrderCommandHandler.cs
> +            _unitOfWork.Commit();
лучше сначала сохранить, а потом очищать корзину. Иначе в случае ошибки сохранения корзина сбросится

2021-02-05 18:14 UTC, max-arshinov commented on Apps/HightechAngular.Web/Features/Cart/AddProductInCart/AddProductInCartCommand.cs
> +        public AddProductInCartCommand(int productId) =>
а зачем этот конструктор в DTO?

2021-02-05 18:14 UTC, max-arshinov commented on Apps/HightechAngular.Web/Features/Cart/RemoveProductInCart/RemoveProductInCartCommand.cs
> +        public RemoveProductInCartCommand(int productId) =>
Зачем этот конструктор?

2021-02-05 18:14 UTC, max-arshinov commented on infrastructure/Infrastructure/Ddd/QueryableFactory.cs
> +        public IQueryable<T> Queryable => _dbContext.Set<T>(); // здесь
Что здесь?

2021-02-06 17:13 UTC, Aleksandr-Naumov commented on Apps/HightechAngular.Web/Features/Account/CreateNewOrder/CreateNewOrderCommandHandler.cs
> +            _unitOfWork.Commit();
Поменял

2021-02-06 17:13 UTC, Aleksandr-Naumov commented on Apps/HightechAngular.Web/Features/Cart/AddProductInCart/AddProductInCartCommand.cs
> +        public AddProductInCartCommand(int productId) =>
убрал

2021-02-06 17:13 UTC, Aleksandr-Naumov commented on Apps/HightechAngular.Web/Features/Cart/RemoveProductInCart/RemoveProductInCartCommand.cs
> +        public RemoveProductInCartCommand(int productId) =>
убрал

2021-02-07 09:44 UTC, max-arshinov commented
Все ок, мержим

2021-02-07 09:52 UTC, merged